-- AlterTable
ALTER TABLE `user` ADD COLUMN `affiliation` ENUM('NEUTRAL', 'JEDI_ORDER', 'SITH_ORDER', 'REBEL_ALLIANCE', 'CIS', 'GALACTIC_REPUBLIC', 'GALACTIC_EMPIRE', 'NEW_REPUBLIC', 'FIRST_ORDER', 'RESISTANCE') NOT NULL DEFAULT 'NEUTRAL';
