-- CreateTable
CREATE TABLE `characters` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `race` ENUM('HUMAN', 'WOOKIEE', 'TWILEK', 'RODIAN', 'ZABRAK', 'TOGRUTA', 'CHISS', 'NAUTOLAN', 'MIRIALAN', 'MON_CALAMARI', 'TRANDOSHAN', 'DROID', 'EWOK', 'HUTT', 'TUSKENS', 'KAMINOAN', 'YODA', 'DATHOMIRIAN') NOT NULL DEFAULT 'HUMAN',
    `affiliation` ENUM('NEUTRAL', 'JEDI_ORDER', 'SITH_ORDER', 'REBEL_ALLIANCE', 'CIS', 'GALACTIC_REPUBLIC', 'GALACTIC_EMPIRE', 'NEW_REPUBLIC', 'FIRST_ORDER', 'RESISTANCE') NOT NULL DEFAULT 'NEUTRAL',
    `homePlanetId` INTEGER NULL,

    UNIQUE INDEX `Character_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `characters` ADD CONSTRAINT `characters_homePlanetId_fkey` FOREIGN KEY (`homePlanetId`) REFERENCES `planet`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
